version: '3.7'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./images/profiles:/var/www/html/images/profiles  # Mount the first upload directory
      - ./images/covers:/var/www/html/images/covers  # Mount the second upload directory
    depends_on:
      - mysql
    entrypoint: ["/bin/sh", "-c", "dockerize -wait tcp://mysql:3306 -timeout 30s apache2-foreground"]


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_perpus
      MYSQL_USER: root
      MYSQL_PASSWORD: passworddb
    ports:
      - "3306:3306"
    volumes:
      - ./data_perpus.sql:/docker-entrypoint-initdb.d/data_perpus.sql