version: '3.7'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./uploads1:/var/www/html/uploads1  # Mount the first upload directory
      - ./uploads2:/var/www/html/uploads2  # Mount the second upload directory
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_perpus
      MYSQL_USER: root
      MYSQL_PASSWORD: passworddb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d