name: Build and Test PHP-Apache-MySQL Docker Container

on:
  push:
    branches:
      - testing2
  pull_request:
    branches:
      - testing2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ReadByte-DigiLib:${{ github.sha }} .

    # Test the container
    - name: Test Container
      run: |
        docker run -d --name ReadByte-DigiLib -p 8080:80 ReadByte-DigiLib:${{ github.sha }}
        sleep 20 # Give services time to start
        curl -f http://localhost:8080 || (docker logs ReadByte-DigiLib && exit 1)

    # Push the Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker tag ReadByte-DigiLib:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ReadByte-DigiLib:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ReadByte-DigiLib:latest