name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - testing2
  pull_request:
    branches:
      - testing2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub using the secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build PHP-Apache Docker image
    - name: Build PHP-Apache Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/readbyte-digilib:latest .

    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/readbyte-digilib:latest